name: map_draw
description: Flutter app for practice with YandexMapkit.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  
  elementary: ^1.3.1
  
  flutter:
    sdk: flutter

  responsive_framework: ^0.2.0

  surf_lint_rules: ^1.5.0


  yandex_mapkit: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: fonts/Nunito-Bold.ttf
          weight: 700
        - asset: fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: fonts/Nunito-Medium.ttf
          weight: 500
        - asset: fonts/Nunito-Regular.ttf
          weight: 400
        - asset: fonts/Nunito-Light.ttf
          weight: 300
        - asset: fonts/Nunito-ExtraLight.ttf
          weight: 200